# Generated by Django 3.0.7 on 2023-06-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230610_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cas',
            field=models.CharField(max_length=30),
        ),
    ]
