# Generated by Django 3.2.15 on 2023-06-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_cas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
