# Generated by Django 3.2.15 on 2023-06-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20230617_1845'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('production_date', models.DateField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bom')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='tcs',
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='freight',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(default='2023-06-19'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='freight',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(default='2023-06-19'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-06-19'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='supplier_no',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='cgst',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='igst',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='sgst',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='veh',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='billno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item', to='transactions.purchasebill'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inventory.stock'),
        ),
        migrations.CreateModel(
            name='ProductionFG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bom', models.FloatField()),
                ('quantity_sfg', models.FloatField()),
                ('production_date', models.DateField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bom')),
                ('sfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.production')),
            ],
        ),
        migrations.CreateModel(
            name='Leadtimesfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rawcode', models.CharField(blank=True, max_length=50, null=True)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('sfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.production')),
            ],
        ),
        migrations.CreateModel(
            name='Leadtimefg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rawcode', models.CharField(blank=True, max_length=50, null=True)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('sfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.productionfg')),
            ],
        ),
        migrations.CreateModel(
            name='FGSFG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_sfg', models.FloatField()),
                ('quantity_raw', models.FloatField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
                ('sfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.production')),
            ],
        ),
        migrations.CreateModel(
            name='BOMRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bom')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
            options={
                'unique_together': {('bom', 'raw_material')},
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='raw_materials',
            field=models.ManyToManyField(through='transactions.BOMRawMaterial', to='inventory.Stock'),
        ),
    ]
