# Generated by Django 3.2.15 on 2023-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230619_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='total_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(default='2023-06-21'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(default='2023-06-21'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-06-21'),
        ),
    ]
