# Generated by Django 3.2.15 on 2023-06-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20230621_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='veh',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
