# Generated by Django 3.2.15 on 2023-06-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_purchasebilldetails_veh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='veh',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(default='2023-06-25'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(default='2023-06-25'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-06-25'),
        ),
    ]
