# Generated by Django 3.0.7 on 2023-06-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_purchaseitem_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='bomrawmaterial',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
