# Generated by Django 3.2.15 on 2023-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20230625_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='code_sfg',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(default='2023-06-28'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(default='2023-06-28'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-06-28'),
        ),
    ]
