# Generated by Django 3.2.15 on 2023-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20230629_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
