# Generated by Django 3.2.15 on 2023-07-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20230708_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(blank=True, default='2023-07-10', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(blank=True, default='2023-07-10', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-07-10'),
        ),
        migrations.AlterField(
            model_name='sfgproduction',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.fgsfg'),
        ),
    ]
