# Generated by Django 3.2.15 on 2023-07-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20230706_1712'),
        ('transactions', '0014_alter_sfgfinal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGSFGNEW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_sfg', models.FloatField()),
                ('quantity_raw', models.FloatField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
                ('sfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bom')),
            ],
        ),
    ]
