# Generated by Django 3.2.15 on 2023-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20230711_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgsfgnew',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
