# Generated by Django 3.2.15 on 2023-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_fgsfgnew_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(blank=True, default='2023-07-12', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(blank=True, default='2023-07-12', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-07-12'),
        ),
    ]
