# Generated by Django 3.2.15 on 2023-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20230712_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='sup_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
