# Generated by Django 3.2.15 on 2023-07-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20230706_1712'),
        ('transactions', '0025_auto_20230713_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fgsfgnew',
            name='raw_material',
        ),
        migrations.AddField(
            model_name='fgsfgnew',
            name='raw_materials',
            field=models.ManyToManyField(to='inventory.Stock'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(blank=True, default='2023-07-14', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(blank=True, default='2023-07-14', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-07-14'),
        ),
    ]
