# Generated by Django 3.2.15 on 2023-07-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_auto_20230715_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialentry',
            old_name='quantity',
            new_name='quantity_raw',
        ),
        migrations.RemoveField(
            model_name='fgsfgnew',
            name='quantity_raw',
        ),
    ]
