# Generated by Django 3.2.15 on 2023-07-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_auto_20230715_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='exp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='mfg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='sup_invoice_no',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
