# Generated by Django 3.2.15 on 2023-08-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_auto_20230715_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fgsfgnew',
            name='quantity_sfg',
        ),
        migrations.RemoveField(
            model_name='fgsfgnew',
            name='sfg',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(blank=True, default='2023-08-04', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(blank=True, default='2023-08-04', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-08-04'),
        ),
        migrations.CreateModel(
            name='MultipleSFG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sfg', models.FloatField()),
                ('fgsfgnew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.fgsfgnew')),
                ('sfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bom')),
            ],
        ),
        migrations.AddField(
            model_name='fgsfgnew',
            name='sfg',
            field=models.ManyToManyField(through='transactions.MultipleSFG', to='transactions.BOM'),
        ),
    ]
