# Generated by Django 3.2.15 on 2023-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_auto_20230804_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='veh',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp_date',
            field=models.DateField(blank=True, default='2023-08-07', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg_date',
            field=models.DateField(blank=True, default='2023-08-07', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-08-07'),
        ),
    ]
