# Generated by Django 3.2.15 on 2023-08-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_auto_20230807_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='time',
            field=models.DateField(default='2023-08-07'),
        ),
    ]
