# Generated by Django 3.2.15 on 2023-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_alter_purchasebill_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='receipt_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
