# Generated by Django 3.2.15 on 2023-08-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_purchasebilldetails_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='purchaseItem',
        ),
    ]
