# Generated by Django 3.2.15 on 2023-08-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_auto_20230808_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='supplier_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
