# Generated by Django 3.2.15 on 2023-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_alter_purchaseitem_supplier_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgproduction',
            name='production_date',
            field=models.DateField(default='2023-08-08'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(default='2023-08-08'),
        ),
    ]
