# Generated by Django 3.2.15 on 2023-08-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_purchasecodecounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseCodeCounter',
        ),
    ]
