# Generated by Django 3.2.15 on 2023-08-08 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20230706_1712'),
        ('transactions', '0044_delete_purchasecodecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='stocks',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock'),
            preserve_default=False,
        ),
    ]
