# Generated by Django 3.2.15 on 2023-08-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_purchasebilldetails_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='purchase_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
