# Generated by Django 3.2.15 on 2023-08-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_auto_20230808_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseCodeCounter',
        ),
    ]
