# Generated by Django 3.2.15 on 2023-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0048_delete_purchasecodecounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='mfg',
        ),
        migrations.AlterField(
            model_name='fgproduction',
            name='production_date',
            field=models.DateField(default='2023-08-09'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(default='2023-08-09'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-08-09'),
        ),
    ]
