# Generated by Django 3.2.15 on 2023-08-09 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0049_auto_20230809_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='exp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='mfg',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
