# Generated by Django 3.2.15 on 2023-08-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0051_auto_20230809_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='exp',
            field=models.DateField(default='2023-08-09'),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='mfg',
            field=models.DateField(default='2023-08-09'),
        ),
    ]
