# Generated by Django 3.2.15 on 2023-08-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0052_auto_20230809_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='exp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='mfg',
            field=models.DateField(),
        ),
    ]
