# Generated by Django 3.2.15 on 2023-08-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0053_auto_20230809_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='exp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='mfg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
