# Generated by Django 3.2.15 on 2023-08-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0054_auto_20230809_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='mfg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
