# Generated by Django 3.2.15 on 2023-08-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0055_auto_20230809_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fgproduction',
            name='production_date',
            field=models.DateField(default='2023-08-10'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(default='2023-08-10'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default='2023-08-10'),
        ),
    ]
