# Generated by Django 3.2.15 on 2023-08-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0056_auto_20230810_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='purchase_item',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='transactions.purchaseitem'),
            preserve_default=False,
        ),
    ]
