# Generated by Django 3.2.15 on 2023-08-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0057_purchasebilldetails_purchase_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item', to='transactions.purchaseitem'),
        ),
    ]
