# Generated by Django 3.2.15 on 2023-08-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0058_alter_purchasebilldetails_purchase_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='purchase_item',
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='purchase_item',
            field=models.ManyToManyField(related_name='purchase_bill_details', to='transactions.PurchaseItem'),
        ),
    ]
