# Generated by Django 3.2.15 on 2023-08-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0059_auto_20230810_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='mfg',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='purchase_item',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='coa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='mfg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
