# Generated by Django 3.2.15 on 2023-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0060_auto_20230810_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='bill_date',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='coa',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='mfg',
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='exp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='mfg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
