# Generated by Django 3.2.15 on 2023-08-12 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0064_auto_20230812_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='exp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mfg',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
