# Generated by Django 3.2.15 on 2023-08-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0065_auto_20230812_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='coa',
        ),
    ]
