# Generated by Django 3.2.15 on 2023-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0066_remove_purchaseitem_coa'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='coa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fgproduction',
            name='production_date',
            field=models.DateField(default='2023-08-13'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(default='2023-08-13'),
        ),
    ]
