# Generated by Django 3.2.15 on 2023-08-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0067_auto_20230813_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='coa',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase_date',
        ),
    ]
