# Generated by Django 3.2.15 on 2023-08-13 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0068_auto_20230813_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='coa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='receipt_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
