# Generated by Django 3.2.15 on 2023-08-13 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0070_auto_20230813_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='invoice',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
