# Generated by Django 3.2.15 on 2023-08-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0071_purchasebilldetails_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='invoice',
            field=models.DateField(default='2023-08-13'),
        ),
    ]
